// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mosahem.Persistence;

#nullable disable

namespace mosahem.Presistence.Migrations
{
    [DbContext(typeof(MosahmDbContext))]
    [Migration("20260121201309_AddAuthTables")]
    partial class AddAuthTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mosahem.Domain.Entities.Identity.OneTimePassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserId");

                    b.HasIndex("Email", "Code");

                    b.ToTable("OneTimePasswords", (string)null);
                });

            modelBuilder.Entity("Mosahem.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Identity.MosahmUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("VolunteerId")
                        .IsUnique()
                        .HasFilter("[VolunteerId] IS NOT NULL");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Governorates", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.MasterData.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.MasterData.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApplicantsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripition")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Vacancies")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Opportunities", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicantStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("OpportunityApplications", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("OpportunityComments", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityField", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OpportunityId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("OpportunityFields", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityLike", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "OpportunityId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("OpportunityLikes", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunitySave", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "OpportunityId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("OpportunitySaves", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunitySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("OpportunityId", "SkillId", "SkillType")
                        .IsUnique();

                    b.ToTable("OpportunitySkills", (string)null);

                    b.HasDiscriminator<int>("SkillType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("mosahem.Domain.Entities.OrganizationField", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("OrganizationFields", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.OrganizationFollower", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationFollowers", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LicenseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VerificationComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompleteOpportunities")
                        .HasColumnType("int");

                    b.Property<string>("CoverImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("ProfileImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId", "Order")
                        .IsUnique();

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Questions.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ChoiceKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("QuestionAnswers", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.VolunteerField", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "FieldId");

                    b.HasIndex("FieldId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerFields", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.VolunteerSkill", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerSkills", (string)null);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityProvideSkill", b =>
                {
                    b.HasBaseType("mosahem.Domain.Entities.Opportunities.OpportunitySkill");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityRequireSkill", b =>
                {
                    b.HasBaseType("mosahem.Domain.Entities.Opportunities.OpportunitySkill");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Mosahem.Domain.Entities.Identity.OneTimePassword", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Identity.MosahmUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mosahem.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Identity.MosahmUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.Address", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Location.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("Address")
                        .HasForeignKey("OpportunityId");

                    b.HasOne("mosahem.Domain.Entities.Profiles.Organization", "Organization")
                        .WithMany("Address")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithOne("Address")
                        .HasForeignKey("mosahem.Domain.Entities.Location.Address", "VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Opportunity");

                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.City", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Location.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.Opportunity", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Profiles.Organization", "Organization")
                        .WithMany("Opportunities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityApplication", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunityApplications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("OpportunityApplications")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityComment", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunityComments")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("OpportunityComments")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityField", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.MasterData.Field", "Field")
                        .WithMany("OpportunityFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunityFields")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunityLike", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunityLikes")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("OpportunityLikes")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunitySave", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunitySaves")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("OpportunitySaves")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.OpportunitySkill", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.MasterData.Skill", "Skill")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.OrganizationField", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.MasterData.Field", "Field")
                        .WithMany("OrganizationFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Organization", "Organization")
                        .WithMany("OrganizationFields")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.OrganizationFollower", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Profiles.Organization", "Organization")
                        .WithMany("OrganizationFollwers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("OrganizationFollwers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Organization", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Identity.MosahmUser", "User")
                        .WithOne("Organization")
                        .HasForeignKey("mosahem.Domain.Entities.Profiles.Organization", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Volunteer", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Identity.MosahmUser", "User")
                        .WithOne("Volunteer")
                        .HasForeignKey("mosahem.Domain.Entities.Profiles.Volunteer", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Questions.Question", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Opportunities.Opportunity", "Opportunity")
                        .WithMany("Questions")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Questions.QuestionAnswer", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.Questions.Question", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.VolunteerField", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.MasterData.Field", "Field")
                        .WithMany("VolunteerFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("VolunteerFields")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.VolunteerSkill", b =>
                {
                    b.HasOne("mosahem.Domain.Entities.MasterData.Skill", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mosahem.Domain.Entities.Profiles.Volunteer", "Volunteer")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Identity.MosahmUser", b =>
                {
                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Location.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.MasterData.Field", b =>
                {
                    b.Navigation("OpportunityFields");

                    b.Navigation("OrganizationFields");

                    b.Navigation("VolunteerFields");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.MasterData.Skill", b =>
                {
                    b.Navigation("OpportunitySkills");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Opportunities.Opportunity", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("OpportunityApplications");

                    b.Navigation("OpportunityComments");

                    b.Navigation("OpportunityFields");

                    b.Navigation("OpportunityLikes");

                    b.Navigation("OpportunitySaves");

                    b.Navigation("OpportunitySkills");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Organization", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Opportunities");

                    b.Navigation("OrganizationFields");

                    b.Navigation("OrganizationFollwers");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Profiles.Volunteer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("OpportunityApplications");

                    b.Navigation("OpportunityComments");

                    b.Navigation("OpportunityLikes");

                    b.Navigation("OpportunitySaves");

                    b.Navigation("OrganizationFollwers");

                    b.Navigation("QuestionAnswers");

                    b.Navigation("VolunteerFields");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("mosahem.Domain.Entities.Questions.Question", b =>
                {
                    b.Navigation("QuestionAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
